"""add pdf_data to resume

Revision ID: 985511903715
Revises: d9df97820159
Create Date: 2025-07-25 08:42:08.348006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985511903715'
down_revision: Union[str, Sequence[str], None] = 'd9df97820159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'pdf_data')
    # ### end Alembic commands ###
