"""add icon column to experience

Revision ID: a166575c0e17
Revises: e475ee644569
Create Date: 2025-07-25 13:58:44.023275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a166575c0e17'
down_revision: Union[str, Sequence[str], None] = 'e475ee644569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'icon')
    # ### end Alembic commands ###
