"""Add icon and color_scheme columns to experience table

Revision ID: c9258e5c099d
Revises: ec6fb992e1fa
Create Date: 2025-07-26 14:40:15.606696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9258e5c099d'
down_revision: Union[str, Sequence[str], None] = 'ec6fb992e1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
