"""add color_scheme column to experience

Revision ID: da1ab52f32ce
Revises: a166575c0e17
Create Date: 2025-07-25 14:16:53.225508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1ab52f32ce'
down_revision: Union[str, Sequence[str], None] = 'a166575c0e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('color_scheme', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'color_scheme')
    # ### end Alembic commands ###
