"""Add ON DELETE CASCADE to project thumbnails

Revision ID: ec6fb992e1fa
Revises: da1ab52f32ce
Create Date: 2025-07-26 12:42:39.427949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6fb992e1fa'
down_revision: Union[str, Sequence[str], None] = 'da1ab52f32ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_thumbnails_project_id_fkey', 'project_thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'project_thumbnails', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_thumbnails', type_='foreignkey')
    op.create_foreign_key('project_thumbnails_project_id_fkey', 'project_thumbnails', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
