"""add_is_approved_to_reviews

Revision ID: fe62c9c355bc
Revises: c9258e5c099d
Create Date: 2025-07-27 10:29:07.083984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe62c9c355bc'
down_revision: Union[str, Sequence[str], None] = 'c9258e5c099d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_approved')
    # ### end Alembic commands ###
